#!/bin/bash

script_preamble() {
    cat <<END_LUA
local __print_lines = {}

local function print(line)
    __print_lines[#__print_lines + 1] = line
end

local ok, err = pcall(function()
END_LUA
}

script_postamble() {
    cat <<END_LUA
end)

if err then
  print(string.format("script threw an error: %s", err))
end

return '\\n' .. table.concat(__print_lines, '\\n') .. '\\n'
END_LUA
}

# XXX prepare the script
#       bundle lib/*.lua
#       replace require
# XXX pipe to dbus-send instead?

( script_preamble ; cat "$1" ; script_postamble ) | awesome-client | tail -n +2 | head -n -1
